### ISSUE TITLE
Output seems to be wrong for a test case. Some issue with the algo.

### ISSUE THREAD

**Issue by raghavddps2** [RohitNagraj/EngineeringCourse#2]
> Enter no. of nodes: 6
Enter adjacency matrix:-
0 1 1 0 0 0
0 0 0 1 1 0
0 0 0 0 1 0
0 0 0 0 1 1
0 0 0 0 0 1
0 0 0 0 0 0
Enter the starting node: 2
The nodes that can be visited are: 3 5 6

Here it shows 3 can be reached from 2, but in this directed graph, it is not even connected. Please check it out and lemme know if i am wrong.

**Comment by RohitNagraj** [comment]
The numbering of the nodes in the output start from 3. Sorry for the inconveniences. Will fix it.
